### ISSUE TITLE
v0.8.10 generates invalid magnet URLs for v2/hybrid torrents

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [alexpdev/TorrentFile#173]
Additionally, `torrentfile magnet` fails on torrent files with no trackers.

Installed from latest git master.

```
$ torrentfile -m --meta-version 2 ytarchive -a udp://explodie.org:6969
ytarchive                                           |██████████████████████████████████████████████████| 7/7 MiB
magnet:?xt=urn:btih:DABCEC469398E3D1A20CFFB15CC993B5FF38C3F762714E6278A24B1926A58CA4&dn=ytarchive&tr=udp%3A%2F%2Fexplodie.org%3A6969

Torrent Save Path:  /home/malloc/ytarchive.torrent
```

v2 hash listed as `urn:btih` component instead of `urn:btmh`, additionally v2 magnet hashes have the prefix `1220`, see https://multiformats.io/multihash/. (it isn't clear to me if this was ever written down as a specification or if people just decided to do it, but qbt rejects unprefixed v2 hashes)

```
$ torrentfile -m --meta-version 3 ytarchive -a udp://explodie.org:6969
ytarchive                                           |██████████████████████████████████████████████████| 7/7 MiB
magnet:?xt=urn:btih:9827DDA0E0DF01194729C6ADFA4085469E67E4858F359BACF6872984CB01EA45&dn=ytarchive&tr=udp%3A%2F%2Fexplodie.org%3A6969

Torrent Save Path:  /home/malloc/ytarchive.torrent
```

Same issue as above, but additionally hybrid torrents should have both `btih` and `btmh`

libtorrent.org provides two test torrents on the bottom of this page with corresponding magnet URLs: https://blog.libtorrent.org/2020/09/bittorrent-v2/

torrentfile can't parse either of them:

```
malloc@host:~$ wget https://libtorrent.org/bittorrent-v2-hybrid-test.torrent
malloc@host:~$ torrentfile magnet bittorrent-v2-hybrid-test.torrent
Traceback (most recent call last):
  File "/home/malloc/.local/bin/torrentfile", line 8, in <module>
    sys.exit(main())
  File "/home/malloc/.local/lib/python3.9/site-packages/torrentfile/cli.py", line 655, in main
    execute()
  File "/home/malloc/.local/lib/python3.9/site-packages/torrentfile/cli.py", line 644, in execute
    return args.func(args)
  File "/home/malloc/.local/lib/python3.9/site-packages/torrentfile/commands.py", line 387, in magnet
    announce_args = ["&tr=" + quote_plus(meta["announce"])]
KeyError: 'announce'
```

qBittorrent 4.5.2 can load both of them and they function as expected. They don't have a tracker specified, which I think is causing the error. Using `transmission-create` to make a v1 torrent with no trackers specified creates files `torrentfile` can't parse, with the above error.

**Comment by alexpdev** [comment]
Good to know... I will fix this and add the new implementation for 0.8.11
