### ISSUE TITLE
info command does not print anything

### ISSUE THREAD

**Issue by pipatron** [alexpdev/TorrentFile#176]
I couldn't get the `info` command to print anything to the console. I took a look into the source code and history and I guess it was broken by c7af6cf:

https://github.com/alexpdev/torrentfile/blob/d3b10170e6eefa5b934ab8a1fd8960812963d3e8/torrentfile/commands.py#L216-L218

https://github.com/alexpdev/torrentfile/blob/c7af6cf5e155085e4109861005958446f3d074a3/torrentfile/commands.py#L238-L240

I don't know if the correct action is to re-add the print or to make sure the logger is set up correctly.

**Comment by alexpdev** [comment]
Thanks for bringing this to my attention.  It tends not to be used to often which makes sense why it hasn't been detected.

The logger is currently set up the way that works best at the moment, the solution would be to directly output the information to the terminal.  Using the standard `print` function would work, or writing the contents directly to `stdout` would work as well.
