### ISSUE TITLE
Support for Piece-Aligned (optimise alignment, BEP-47) ?

### ISSUE THREAD

**Issue by predb** [alexpdev/TorrentFile#183]
Torrents containing multi files often get stuck at 99.x% if not piece-aligned when creating.
Could u plz support this feature (Based on BT protocol BEP-47) ? thanks.

>**Padding files and extended file attributes**.
>[https://www.bittorrent.org/beps/bep_0047.html](url)
>Padding files are synthetic files inserted into the file list to let the following file start at a piece boundary. That means their length should fill up the remainder of the piece length of the file that is supposed to be padded. 

Related Information: 
https://forum.qbittorrent.org/viewtopic.php?p=41005#p41005

**Comment by alexpdev** [comment]
@predb 
can you send me an example of a file that gets stuck at 99.x?

-------------------
EDIT
I understand the issue.  I will try to fix this soon.

**Comment by predb** [comment]
> @predb can you send me an example of a file that gets stuck at 99.x?
> 
> EDIT I understand the issue. I will try to fix this soon.

yes. An additional option for creating v1 torrent.

**Comment by alexpdev** [comment]
@predb 
I just merged 0.9.1 and updated uploaded it to PyPi.  You can now use the `--align` command line flag when creating version 1 torrents to force them to piece align to file boundaries.
